// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mq.proto

package go_mymicro_proto_mq

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MQMessage struct {
	DeviceId             int64    `protobuf:"varint,1,opt,name=DeviceId,proto3" json:"DeviceId,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	CodeType             int32    `protobuf:"varint,3,opt,name=CodeType,proto3" json:"CodeType,omitempty"`
	PbMessage            []byte   `protobuf:"bytes,4,opt,name=PbMessage,proto3" json:"PbMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MQMessage) Reset()         { *m = MQMessage{} }
func (m *MQMessage) String() string { return proto.CompactTextString(m) }
func (*MQMessage) ProtoMessage()    {}
func (*MQMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_7caa8199c0db1966, []int{0}
}

func (m *MQMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MQMessage.Unmarshal(m, b)
}
func (m *MQMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MQMessage.Marshal(b, m, deterministic)
}
func (m *MQMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MQMessage.Merge(m, src)
}
func (m *MQMessage) XXX_Size() int {
	return xxx_messageInfo_MQMessage.Size(m)
}
func (m *MQMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_MQMessage.DiscardUnknown(m)
}

var xxx_messageInfo_MQMessage proto.InternalMessageInfo

func (m *MQMessage) GetDeviceId() int64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func (m *MQMessage) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *MQMessage) GetCodeType() int32 {
	if m != nil {
		return m.CodeType
	}
	return 0
}

func (m *MQMessage) GetPbMessage() []byte {
	if m != nil {
		return m.PbMessage
	}
	return nil
}

func init() {
	proto.RegisterType((*MQMessage)(nil), "go.mymicro.proto.mq.MQMessage")
}

func init() { proto.RegisterFile("mq.proto", fileDescriptor_7caa8199c0db1966) }

var fileDescriptor_7caa8199c0db1966 = []byte{
	// 141 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc8, 0x2d, 0xd4, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x4e, 0xcf, 0xd7, 0xcb, 0xad, 0xcc, 0xcd, 0x4c, 0x2e, 0xca,
	0x87, 0x88, 0xe8, 0xe5, 0x16, 0x2a, 0x55, 0x72, 0x71, 0xfa, 0x06, 0xfa, 0xa6, 0x16, 0x17, 0x27,
	0xa6, 0xa7, 0x0a, 0x49, 0x71, 0x71, 0xb8, 0xa4, 0x96, 0x65, 0x26, 0xa7, 0x7a, 0xa6, 0x48, 0x30,
	0x2a, 0x30, 0x6a, 0x30, 0x07, 0xc1, 0xf9, 0x42, 0x62, 0x5c, 0x6c, 0xa1, 0xc5, 0xa9, 0x45, 0x9e,
	0x29, 0x12, 0x4c, 0x60, 0x19, 0x28, 0x0f, 0xa4, 0xc7, 0x39, 0x3f, 0x25, 0x35, 0xa4, 0xb2, 0x20,
	0x55, 0x82, 0x59, 0x81, 0x51, 0x83, 0x35, 0x08, 0xce, 0x17, 0x92, 0xe1, 0xe2, 0x0c, 0x48, 0x82,
	0x1a, 0x2e, 0xc1, 0xa2, 0xc0, 0xa8, 0xc1, 0x13, 0x84, 0x10, 0x48, 0x62, 0x03, 0x3b, 0xc2, 0x18,
	0x10, 0x00, 0x00, 0xff, 0xff, 0x72, 0x9f, 0x5f, 0x04, 0xa2, 0x00, 0x00, 0x00,
}
