// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package go_mymicro_proto_message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SingleMessage struct {
	From                 int64    `protobuf:"varint,1,opt,name=From,proto3" json:"From,omitempty"`
	To                   int64    `protobuf:"varint,2,opt,name=To,proto3" json:"To,omitempty"`
	Seq                  int64    `protobuf:"varint,3,opt,name=Seq,proto3" json:"Seq,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleMessage) Reset()         { *m = SingleMessage{} }
func (m *SingleMessage) String() string { return proto.CompactTextString(m) }
func (*SingleMessage) ProtoMessage()    {}
func (*SingleMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *SingleMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleMessage.Unmarshal(m, b)
}
func (m *SingleMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleMessage.Marshal(b, m, deterministic)
}
func (m *SingleMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleMessage.Merge(m, src)
}
func (m *SingleMessage) XXX_Size() int {
	return xxx_messageInfo_SingleMessage.Size(m)
}
func (m *SingleMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SingleMessage proto.InternalMessageInfo

func (m *SingleMessage) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *SingleMessage) GetTo() int64 {
	if m != nil {
		return m.To
	}
	return 0
}

func (m *SingleMessage) GetSeq() int64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *SingleMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SingleMessageAck struct {
	Seq                  int64    `protobuf:"varint,1,opt,name=Seq,proto3" json:"Seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleMessageAck) Reset()         { *m = SingleMessageAck{} }
func (m *SingleMessageAck) String() string { return proto.CompactTextString(m) }
func (*SingleMessageAck) ProtoMessage()    {}
func (*SingleMessageAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *SingleMessageAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleMessageAck.Unmarshal(m, b)
}
func (m *SingleMessageAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleMessageAck.Marshal(b, m, deterministic)
}
func (m *SingleMessageAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleMessageAck.Merge(m, src)
}
func (m *SingleMessageAck) XXX_Size() int {
	return xxx_messageInfo_SingleMessageAck.Size(m)
}
func (m *SingleMessageAck) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleMessageAck.DiscardUnknown(m)
}

var xxx_messageInfo_SingleMessageAck proto.InternalMessageInfo

func (m *SingleMessageAck) GetSeq() int64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func init() {
	proto.RegisterType((*SingleMessage)(nil), "go.mymicro.proto.message.SingleMessage")
	proto.RegisterType((*SingleMessageAck)(nil), "go.mymicro.proto.message.SingleMessageAck")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 145 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0x48, 0xcf, 0xd7, 0xcb, 0xad,
	0xcc, 0xcd, 0x4c, 0x2e, 0xca, 0x87, 0x88, 0xe8, 0x41, 0xe5, 0x95, 0xe2, 0xb9, 0x78, 0x83, 0x33,
	0xf3, 0xd2, 0x73, 0x52, 0x7d, 0x21, 0x02, 0x42, 0x42, 0x5c, 0x2c, 0x6e, 0x45, 0xf9, 0xb9, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0xcc, 0x41, 0x60, 0xb6, 0x10, 0x1f, 0x17, 0x53, 0x48, 0xbe, 0x04, 0x13,
	0x58, 0x84, 0x29, 0x24, 0x5f, 0x48, 0x80, 0x8b, 0x39, 0x38, 0xb5, 0x50, 0x82, 0x19, 0x2c, 0x00,
	0x62, 0x0a, 0x49, 0x70, 0xb1, 0x43, 0x0d, 0x90, 0x60, 0x51, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x71,
	0x95, 0x54, 0xb8, 0x04, 0x50, 0x2c, 0x70, 0x4c, 0xce, 0x86, 0xe9, 0x67, 0x84, 0xeb, 0x4f, 0x62,
	0x03, 0xbb, 0xca, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xad, 0x0a, 0xe0, 0x7d, 0xb8, 0x00, 0x00,
	0x00,
}
