// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package go_mymicro_srv_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	DeviceId             string   `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserPassword         string   `protobuf:"bytes,3,opt,name=user_password,json=userPassword,proto3" json:"user_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *Request) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *Request) GetUserPassword() string {
	if m != nil {
		return m.UserPassword
	}
	return ""
}

type Response struct {
	ResCode              int32    `protobuf:"varint,1,opt,name=res_code,json=resCode,proto3" json:"res_code,omitempty"`
	ResMsg               string   `protobuf:"bytes,2,opt,name=res_msg,json=resMsg,proto3" json:"res_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetResCode() int32 {
	if m != nil {
		return m.ResCode
	}
	return 0
}

func (m *Response) GetResMsg() string {
	if m != nil {
		return m.ResMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "go.mymicro.srv.user.Request")
	proto.RegisterType((*Response)(nil), "go.mymicro.srv.user.Response")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x39, 0x4f, 0xc4, 0x30,
	0x10, 0x85, 0x59, 0x8e, 0x6c, 0x76, 0x04, 0x8d, 0x29, 0x08, 0x97, 0x84, 0x42, 0x43, 0xe5, 0x02,
	0x7a, 0x1a, 0x0a, 0xb4, 0x05, 0x87, 0x8c, 0xa8, 0xad, 0x10, 0x8f, 0x8c, 0x0b, 0x7b, 0xc2, 0xcc,
	0x6e, 0x10, 0xff, 0x1e, 0xd9, 0x49, 0x09, 0x9d, 0xf5, 0x7d, 0x4f, 0x7a, 0x7e, 0x03, 0xb0, 0x15,
	0x64, 0x3d, 0x30, 0x6d, 0x48, 0x1d, 0x7b, 0xd2, 0xf1, 0x27, 0x86, 0x9e, 0x49, 0x0b, 0x8f, 0x3a,
	0xab, 0xf6, 0x13, 0x96, 0x06, 0xbf, 0xb6, 0x28, 0x1b, 0x75, 0x0e, 0x2b, 0x87, 0x63, 0xe8, 0xd1,
	0x06, 0xd7, 0x2c, 0xae, 0x16, 0x37, 0x2b, 0x53, 0x4f, 0x60, 0xed, 0xb2, 0xcc, 0x79, 0x9b, 0xba,
	0x88, 0xcd, 0xee, 0x24, 0x33, 0x78, 0xee, 0x22, 0xaa, 0x6b, 0x38, 0x2a, 0x72, 0xe8, 0x44, 0xbe,
	0x89, 0x5d, 0xb3, 0x57, 0x02, 0x87, 0x19, 0xbe, 0xce, 0xac, 0xbd, 0x87, 0xda, 0xa0, 0x0c, 0x94,
	0x04, 0xd5, 0x29, 0xd4, 0x8c, 0x62, 0x7b, 0x72, 0x58, 0x9a, 0x0e, 0xcc, 0x92, 0x51, 0x1e, 0xc8,
	0xa1, 0x3a, 0x81, 0xfc, 0xb4, 0x51, 0xfc, 0x5c, 0x53, 0x31, 0xca, 0x93, 0xf8, 0xdb, 0x17, 0xd8,
	0x7f, 0x17, 0x64, 0xf5, 0x08, 0xd5, 0x5b, 0xf0, 0x69, 0x9d, 0xd4, 0x85, 0xfe, 0x63, 0x91, 0x9e,
	0xe7, 0x9c, 0x5d, 0xfe, 0x63, 0xa7, 0x2f, 0xb4, 0x3b, 0x1f, 0x55, 0x39, 0xcb, 0xdd, 0x6f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xa5, 0x42, 0x10, 0x35, 0x24, 0x01, 0x00, 0x00,
}
